---
title: "Use Cases"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Use Cases}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

We are creating a collection of projects using COVID-19 Data Hub. Don't hesitate to comment below and let us know about your project. We are happy to showcase your work here. Featured projects using COVID-19 Data Hub:

- [Are official confirmed cases and fatalities counts good enough to study the COVID–19 pandemic dynamics? A critical assessment through the case of Italy](https://rdcu.be/b5g5V)
- [CovsirPhy: Python package for COVID-19 analysis with SIR-derived ODE models](https://github.com/lisphilar/covid19-sir)
- [Mirai Solutions Dashboard](https://mirai-solutions.ch/gallery/covid19/)
- [Brazilian COVID-19 Dashboard](https://app.powerbi.com/view?r=eyJrIjoiNWExN2JlMzQtNTBiOC00ODU5LWIxY2QtODQwZTNhMjQzNGJmIiwidCI6ImMzN2IzN2EzLWU5ZTItNDJmOS1iYzY3LTRiOWI3MzhlMWRmMCJ9)
- [Prof. Malouche Dashboard](https://malouche.github.io/covid19data/)
- [Coronawhy database](https://www.coronawhy.org/)
- [Covid19 Incidence History](http://emit.phys.ocean.dal.ca/~kelley/covid19/)

See also the [publications](https://scholar.google.com/scholar?oi=bibs&hl=en&cites=1585537563493742217) that use the COVID-19 Data Hub.

COVID-19 Data Hub press releases:

- [HEC Montréal](https://www.hec.ca/en/research/take-a-closer-look/reliable-unified-data.html) 
- [Statistical Society of Canada](https://ssc.ca/en/publications/ssc-liaison/vol-34-3-june-2020/news-hec-montreal)
- [Quartier L!bre](https://quartierlibre.ca/regrouper-les-donnees-mondiales-sur-la-covid-19/)

__Using COVID-19 Data Hub?__ Open a [GitHub issue](https://github.com/covid19datahub/COVID19/issues) or comment below to let us know about your project. We are happy to showcase your work here.


`r gsub("^# ", "## ", readr::read_file('../LICENSE.md'))`
