#'
#' Datasets Citation
#'
#' Cite the data sources used by the \link{covid19} function.  
#'
#' @param x dataset generated by the \link{covid19} function.
#' @param bibtex logical. Bibtex output? Default \code{FALSE}.
#' @param verbose logical. Print citations? Default \code{TRUE}.
#'
#' @return \code{data.frame} of data sources used by the \link{covid19} function.  
#'
#' @examples
#' \dontrun{
#'
#' # Worldwide data by country
#' x   <- covid19()
#' cit <- covid19cite(x)
#' View(cit)
#'
#' }
#'
#' @export
#'
covid19cite <- function(x, bibtex = FALSE, verbose = TRUE){
  
  src <- db("_src")

  x <- x %>% 
    
    dplyr::group_by(id) %>%
    
    dplyr::group_map(keep = TRUE, function(x, g){
      
      id    <- strsplit(x$id[1], ", ")[[1]]
      iso   <- id[1]
      level <- 1 + any(!is.na(x$state)) + any(!is.na(x$city))
      
      var <- apply(x, 2, function(x) !all(is.na(x) | x==0))
      var <- names(var)[var]
      
      s <- merge(src, data.frame(iso = iso, level = level, var = var))
      
      var <- var[!(var %in% s$var)]
      if(length(var)>0)
        s <- s %>% 
          dplyr::bind_rows(merge(src, data.frame(iso = NA, level = NA, var = var)))
      
      s$iso[is.na(s$iso)] <- iso
      s$level[is.na(s$level)] <- level
      
      return(s)
      
    }) %>%
    
    dplyr::bind_rows()
  
    x <- x[!duplicated(x),]
    y <- x[!duplicated(x[,c('title')]),]
    y <- apply(y, 1, function(y){
      
      textVersion <- y['textVersion']
      if(is.na(textVersion))
        textVersion <- NULL
      
      utils::bibentry(
        bibtype     = ifelse(is.na(y['bibtype']), "Misc", y['bibtype']),
        note        = y['note'],
        title       = y['title'], 
        year        = y['year'], 
        author      = y['author'],
        institution = y['institution'], 
        textVersion = textVersion
      )  
      
    })
    
    cit <- utils::citation("COVID19")
    for(i in 1:length(y))
      cit <- c(y[[i]], cit)
     
    if(verbose) 
      print(cit, style = "citation", bibtex = bibtex)
    
    return(x)
    
}